version: 1.4.1-{build}

skip_tags: false

clone_folder: C:\rust-embed-resource

environment:
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      MINGW: true
      TOOLCHAIN: stable
    - TARGET: x86_64-pc-windows-gnu
      MINGW: true
      TOOLCHAIN: 1.35.0
    - TARGET: x86_64-pc-windows-msvc
      TOOLCHAIN: stable
    - TARGET: x86_64-pc-windows-msvc
      TOOLCHAIN: 1.35.0

install:
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MINGW set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  # https://www.msys2.org/news/#2020-05-17-32-bit-msys2-no-longer-actively-supported
  - if defined MINGW curl -SL http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz -oC:\msys2-keyring.txz
  - if defined MINGW curl -SL http://repo.msys2.org/msys/x86_64/zstd-1.4.4-2-x86_64.pkg.tar.xz -oC:\zstd.txz
  - if defined MINGW curl -SL http://repo.msys2.org/msys/x86_64/pacman-5.2.2-5-x86_64.pkg.tar.xz -oC:\pacman.txz
  - if defined MINGW pacman --noconfirm -U C:\msys2-keyring.txz
  - if defined MINGW pacman --noconfirm -U C:\zstd.txz
  - if defined MINGW pacman --noconfirm -U C:\pacman.txz
  - if defined MINGW bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - if defined MINGW bash -lc "pacman --noconfirm -Sy pacman"
  - if defined MINGW bash -lc "pacman --noconfirm -Su"
  - if defined MINGW bash -lc "pacman --noconfirm -Sy"
  - if defined MINGW bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="%TARGET%" --default-toolchain="%TOOLCHAIN%"

build: off
build_script:
  - cargo build --verbose --release

test: off
test_script:
  - cargo test --verbose --release
  - cargo run --verbose --release -- empty-resource.rc

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
