version: 1.2.0-{build}

skip_tags: false

clone_folder: C:\rust-embed-resource

environment:
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      MINGW: true
    - TARGET: x86_64-pc-windows-msvc

install:
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MINGW set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - if defined MINGW bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - if defined MINGW bash -lc "pacman --noconfirm -Sy"
  - if defined MINGW bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="%TARGET%"

build: off
build_script:
  - cargo build --verbose --release

test: off
test_script:
  - cargo test --verbose --release
  - cargo run --verbose --release -- empty-resource.rc

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
